Edge cases and Tests
keronei/iReporter pull request #16
Opened 2018-12-04 09:20 UTC by keronei

This is an implementation of various edge cases in order to keep the api's at check and prevent crashes during runtime.
The following is an highlight of what is taken care off:

1. User attempting to create an entry while providing less params.
2. Requesting deletion without providing an `identifier`(key) for the particular entry.
3.Attempting update to an entry without the `identifier`. 
4.Differentiating `GET` requests for a single entry and all entries, this employs an identifier param that is set to `null`, which by default serves the user with all entries, however, when a the param is supplied, the user is replied with a single entry, in cases where a match is successfully found.

This PR furthermore contains tests for the particular cases that have been handled.

2018-12-04 09:58 UTC, thoth-ky requested changes
Kindly act on the feedback I have left below.

2018-12-04 09:58 UTC, jmutuku95 commented on app/__init__.py
> +    app.config.from_object(app_config['development'])
make this dynamic. As it is it will always open the app in `development` environment

2018-12-04 09:58 UTC, jmutuku95 commented on app/tests/v1/test.py
>  app = launcher()
At this point you should be passing the environment, in this case `testing` so that it picks up relevant config. In line with changes suggested in the launcher function

2018-12-04 09:58 UTC, jmutuku95 commented on app/tests/v1/test.py
> +            self.assertEqual(response.status_code,200,"Success on post should be 204")
Test contents of the response. Not just the status code

2018-12-04 09:58 UTC, jmutuku95 commented on app/tests/v1/test.py
> +        with app.test_request_context():
NOt necessary if you make your `launcher` function dynamic

2018-12-04 09:58 UTC, jmutuku95 commented on app/tests/v1/test.py
>      def test_deletion(self):
deletion of what? Make your test names self documenting like `test_can_delete_red_flag`

2018-12-04 15:09 UTC, jmutuku95 commented
Add test for more edge cases, like what happens when one tries to fetch some record that is not there or gives unvalidated data to create a record?

2018-12-04 15:25 UTC, keronei commented on app/__init__.py
> +    app.config.from_object(app_config['development'])
Have implemented in the this format:

`app = launcher(app_config["development"])`

Which will take Production environment if no specification is made.

2018-12-04 15:26 UTC, keronei commented on app/tests/v1/test.py
> +            self.assertEqual(response.status_code,200,"Success on post should be 204")
Have included assertions for the expected content.

2018-12-04 15:27 UTC, keronei commented on app/tests/v1/test.py
> +        with app.test_request_context():
Haven't figured out how to have the function dynamic, but will seek advise of the same and implement.

2018-12-04 15:28 UTC, keronei commented on app/tests/v1/test.py
>      def test_deletion(self):
Have refactored the namings to speak for themselves. With meaningful names now.

2018-12-05 06:50 UTC, thoth-ky approved these changes
Add travis on this branch so that we kow if the tests are passing.

2018-12-05 06:51 UTC, jmutuku95 commented on app/__init__.py
> +from .api.v2 import version_two as v2
without a v2, this will throw an error

2018-12-05 06:53 UTC, jmutuku95 commented on requirements.txt
> +SQLAlchemy==1.2.14
Remove this because we will not be using ORM

2018-12-05 06:53 UTC, jmutuku95 commented on requirements.txt
> +Flask-SQLAlchemy==2.3.2
This too

2018-12-05 06:53 UTC, jmutuku95 commented on requirements.txt
> +alembic==1.0.5
```suggestion
```
Remove all ORM related dependencies

2018-12-05 06:55 UTC, thoth-ky requested changes
Act on feedback left. Also mantainability is pretty low

2018-12-05 08:11 UTC, merged